/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiGateway);
  }
}(this, function(expect, ApiGateway) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiGateway.InlineResponse2007OrderPaymentDataFromCard();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2007OrderPaymentDataFromCard', function() {
    it('should create an instance of InlineResponse2007OrderPaymentDataFromCard', function() {
      // uncomment below and update the code to test InlineResponse2007OrderPaymentDataFromCard
      //var instance = new ApiGateway.InlineResponse2007OrderPaymentDataFromCard();
      //expect(instance).to.be.a(ApiGateway.InlineResponse2007OrderPaymentDataFromCard);
    });

    it('should have the property cardBrand (base name: "card_brand")', function() {
      // uncomment below and update the code to test the property cardBrand
      //var instance = new ApiGateway.InlineResponse2007OrderPaymentDataFromCard();
      //expect(instance).to.be();
    });

    it('should have the property firstSix (base name: "first_six")', function() {
      // uncomment below and update the code to test the property firstSix
      //var instance = new ApiGateway.InlineResponse2007OrderPaymentDataFromCard();
      //expect(instance).to.be();
    });

    it('should have the property lastFour (base name: "last_four")', function() {
      // uncomment below and update the code to test the property lastFour
      //var instance = new ApiGateway.InlineResponse2007OrderPaymentDataFromCard();
      //expect(instance).to.be();
    });

  });

}));
