/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiGateway);
  }
}(this, function(expect, ApiGateway) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiGateway.InlineResponse2004ShippingOption();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2004ShippingOption', function() {
    it('should create an instance of InlineResponse2004ShippingOption', function() {
      // uncomment below and update the code to test InlineResponse2004ShippingOption
      //var instance = new ApiGateway.InlineResponse2004ShippingOption();
      //expect(instance).to.be.a(ApiGateway.InlineResponse2004ShippingOption);
    });

    it('should have the property cost (base name: "cost")', function() {
      // uncomment below and update the code to test the property cost
      //var instance = new ApiGateway.InlineResponse2004ShippingOption();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new ApiGateway.InlineResponse2004ShippingOption();
      //expect(instance).to.be();
    });

    it('should have the property estimatedDeliveryDate (base name: "estimated_delivery_date")', function() {
      // uncomment below and update the code to test the property estimatedDeliveryDate
      //var instance = new ApiGateway.InlineResponse2004ShippingOption();
      //expect(instance).to.be();
    });

    it('should have the property reference (base name: "reference")', function() {
      // uncomment below and update the code to test the property reference
      //var instance = new ApiGateway.InlineResponse2004ShippingOption();
      //expect(instance).to.be();
    });

    it('should have the property serviceName (base name: "service_name")', function() {
      // uncomment below and update the code to test the property serviceName
      //var instance = new ApiGateway.InlineResponse2004ShippingOption();
      //expect(instance).to.be();
    });

    it('should have the property taxAmount (base name: "tax_amount")', function() {
      // uncomment below and update the code to test the property taxAmount
      //var instance = new ApiGateway.InlineResponse2004ShippingOption();
      //expect(instance).to.be();
    });

    it('should have the property taxCode (base name: "tax_code")', function() {
      // uncomment below and update the code to test the property taxCode
      //var instance = new ApiGateway.InlineResponse2004ShippingOption();
      //expect(instance).to.be();
    });

  });

}));
