/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiGateway);
  }
}(this, function(expect, ApiGateway) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiGateway.MerchantsOrdersOrderShippingOptionsDetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MerchantsOrdersOrderShippingOptionsDetails', function() {
    it('should create an instance of MerchantsOrdersOrderShippingOptionsDetails', function() {
      // uncomment below and update the code to test MerchantsOrdersOrderShippingOptionsDetails
      //var instance = new ApiGateway.MerchantsOrdersOrderShippingOptionsDetails();
      //expect(instance).to.be.a(ApiGateway.MerchantsOrdersOrderShippingOptionsDetails);
    });

    it('should have the property additionalDetails (base name: "additional_details")', function() {
      // uncomment below and update the code to test the property additionalDetails
      //var instance = new ApiGateway.MerchantsOrdersOrderShippingOptionsDetails();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instance = new ApiGateway.MerchantsOrdersOrderShippingOptionsDetails();
      //expect(instance).to.be();
    });

    it('should have the property addressCoordinates (base name: "address_coordinates")', function() {
      // uncomment below and update the code to test the property addressCoordinates
      //var instance = new ApiGateway.MerchantsOrdersOrderShippingOptionsDetails();
      //expect(instance).to.be();
    });

    it('should have the property contact (base name: "contact")', function() {
      // uncomment below and update the code to test the property contact
      //var instance = new ApiGateway.MerchantsOrdersOrderShippingOptionsDetails();
      //expect(instance).to.be();
    });

    it('should have the property storeName (base name: "store_name")', function() {
      // uncomment below and update the code to test the property storeName
      //var instance = new ApiGateway.MerchantsOrdersOrderShippingOptionsDetails();
      //expect(instance).to.be();
    });

  });

}));
