/**
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse200OrderMetadata } from './InlineResponse200OrderMetadata';
import { InlineResponse200OrderShippingAddress } from './InlineResponse200OrderShippingAddress';
import { InlineResponse200OrderShippingOptions } from './InlineResponse200OrderShippingOptions';
import { Set } from './Set';
import { HttpFile } from '../http/http';

export class InlineResponse200Order {
    'currency': string;
    'discounts': Set<any>;
    'displayItemsTotalAmount': string;
    'displayShippingAmount': string;
    'displaySubTotal': string;
    'displayTaxAmount': string;
    'displayTotalAmount': string;
    'items': Set<any>;
    'itemsTotalAmount': number;
    'metadata': InlineResponse200OrderMetadata;
    'orderId': string;
    'payment'?: any;
    'shippingAddress': InlineResponse200OrderShippingAddress;
    'shippingAmount': number;
    'shippingOptions': InlineResponse200OrderShippingOptions;
    'status': string;
    'storeCode': string;
    'subTotal': number;
    'taxAmount': number;
    'totalAmount': number;
    'userInstructions': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "discounts",
            "baseName": "discounts",
            "type": "Set<any>",
            "format": ""
        },
        {
            "name": "displayItemsTotalAmount",
            "baseName": "display_items_total_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayShippingAmount",
            "baseName": "display_shipping_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "displaySubTotal",
            "baseName": "display_sub_total",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayTaxAmount",
            "baseName": "display_tax_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayTotalAmount",
            "baseName": "display_total_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Set<any>",
            "format": ""
        },
        {
            "name": "itemsTotalAmount",
            "baseName": "items_total_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "InlineResponse200OrderMetadata",
            "format": ""
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "payment",
            "baseName": "payment",
            "type": "any",
            "format": ""
        },
        {
            "name": "shippingAddress",
            "baseName": "shipping_address",
            "type": "InlineResponse200OrderShippingAddress",
            "format": ""
        },
        {
            "name": "shippingAmount",
            "baseName": "shipping_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "shippingOptions",
            "baseName": "shipping_options",
            "type": "InlineResponse200OrderShippingOptions",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "storeCode",
            "baseName": "store_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "subTotal",
            "baseName": "sub_total",
            "type": "number",
            "format": ""
        },
        {
            "name": "taxAmount",
            "baseName": "tax_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalAmount",
            "baseName": "total_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "userInstructions",
            "baseName": "user_instructions",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse200Order.attributeTypeMap;
    }

    public constructor() {
    }
}

