/**
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse2001OrderShippingOptionsDetails } from './InlineResponse2001OrderShippingOptionsDetails';
import { HttpFile } from '../http/http';

export class InlineResponse2001OrderShippingOptions {
    'details'?: InlineResponse2001OrderShippingOptionsDetails;
    'type'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "details",
            "baseName": "details",
            "type": "InlineResponse2001OrderShippingOptionsDetails",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2001OrderShippingOptions.attributeTypeMap;
    }

    public constructor() {
    }
}

