/**
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse2002Order } from './InlineResponse2002Order';
import { Set } from './Set';
import { HttpFile } from '../http/http';

export class InlineResponse2002 {
    'order'?: InlineResponse2002Order;
    'shippingMethods'?: Set<any>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "order",
            "baseName": "order",
            "type": "InlineResponse2002Order",
            "format": ""
        },
        {
            "name": "shippingMethods",
            "baseName": "shipping_methods",
            "type": "Set<any>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2002.attributeTypeMap;
    }

    public constructor() {
    }
}

