/**
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class InlineResponse2004ShippingOption {
    'cost': number;
    'description': string;
    'estimatedDeliveryDate': string;
    'reference': string;
    'serviceName': string;
    'taxAmount': number;
    'taxCode': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cost",
            "baseName": "cost",
            "type": "number",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "estimatedDeliveryDate",
            "baseName": "estimated_delivery_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceName",
            "baseName": "service_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "taxAmount",
            "baseName": "tax_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "taxCode",
            "baseName": "tax_code",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2004ShippingOption.attributeTypeMap;
    }

    public constructor() {
    }
}

