/**
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse2007OrderPaymentData } from './InlineResponse2007OrderPaymentData';
import { HttpFile } from '../http/http';

export class InlineResponse2007OrderPayment {
    'data': InlineResponse2007OrderPaymentData;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "InlineResponse2007OrderPaymentData",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2007OrderPayment.attributeTypeMap;
    }

    public constructor() {
    }
}

