/**
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse2004Order } from './InlineResponse2004Order';
import { InlineResponse2004ShippingOption } from './InlineResponse2004ShippingOption';
import { HttpFile } from '../http/http';

export class InlineResponse2004 {
    'order'?: InlineResponse2004Order;
    'shippingOption'?: InlineResponse2004ShippingOption;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "order",
            "baseName": "order",
            "type": "InlineResponse2004Order",
            "format": ""
        },
        {
            "name": "shippingOption",
            "baseName": "shipping_option",
            "type": "InlineResponse2004ShippingOption",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2004.attributeTypeMap;
    }

    public constructor() {
    }
}

