/**
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class InlineResponse2007OrderPaymentDataFromCard {
    'cardBrand': string;
    'firstSix': string;
    'lastFour': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cardBrand",
            "baseName": "card_brand",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstSix",
            "baseName": "first_six",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastFour",
            "baseName": "last_four",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2007OrderPaymentDataFromCard.attributeTypeMap;
    }

    public constructor() {
    }
}

