/**
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MerchantsTransactionsPurchaseCreditCard } from './MerchantsTransactionsPurchaseCreditCard';
import { MerchantsTransactionsPurchaseSpecificFields } from './MerchantsTransactionsPurchaseSpecificFields';
import { HttpFile } from '../http/http';

export class InlineObject6 {
    'billingAddress'?: any;
    'callbackUrl'?: string;
    'creditCard'?: MerchantsTransactionsPurchaseCreditCard;
    'deviceId'?: string;
    'email'?: string;
    'methodType'?: string;
    'shippingAddress'?: any;
    'specificFields'?: MerchantsTransactionsPurchaseSpecificFields;
    'storeCode'?: string;
    'token'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "billingAddress",
            "baseName": "billing_address",
            "type": "any",
            "format": ""
        },
        {
            "name": "callbackUrl",
            "baseName": "callback_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "creditCard",
            "baseName": "credit_card",
            "type": "MerchantsTransactionsPurchaseCreditCard",
            "format": ""
        },
        {
            "name": "deviceId",
            "baseName": "device_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "methodType",
            "baseName": "method_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "shippingAddress",
            "baseName": "shipping_address",
            "type": "any",
            "format": ""
        },
        {
            "name": "specificFields",
            "baseName": "specific_fields",
            "type": "MerchantsTransactionsPurchaseSpecificFields",
            "format": ""
        },
        {
            "name": "storeCode",
            "baseName": "store_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineObject6.attributeTypeMap;
    }

    public constructor() {
    }
}

