/**
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse2001OrderShippingOptionsDetailsAddressCoordinates } from './InlineResponse2001OrderShippingOptionsDetailsAddressCoordinates';
import { InlineResponse2001OrderShippingOptionsDetailsContact } from './InlineResponse2001OrderShippingOptionsDetailsContact';
import { HttpFile } from '../http/http';

export class InlineResponse2002OrderShippingOptionsDetails {
    'additionalDetails'?: any;
    'address'?: string;
    'addressCoordinates'?: InlineResponse2001OrderShippingOptionsDetailsAddressCoordinates;
    'contact'?: InlineResponse2001OrderShippingOptionsDetailsContact;
    'storeName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "additionalDetails",
            "baseName": "additional_details",
            "type": "any",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressCoordinates",
            "baseName": "address_coordinates",
            "type": "InlineResponse2001OrderShippingOptionsDetailsAddressCoordinates",
            "format": ""
        },
        {
            "name": "contact",
            "baseName": "contact",
            "type": "InlineResponse2001OrderShippingOptionsDetailsContact",
            "format": ""
        },
        {
            "name": "storeName",
            "baseName": "store_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2002OrderShippingOptionsDetails.attributeTypeMap;
    }

    public constructor() {
    }
}

