/**
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class InlineResponse2001OrderShippingOptionsDetailsAdditionalDetails {
    'pickupTime'?: string;
    'stockLocation'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pickupTime",
            "baseName": "pickup_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "stockLocation",
            "baseName": "stock_location",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2001OrderShippingOptionsDetailsAdditionalDetails.attributeTypeMap;
    }

    public constructor() {
    }
}

