/**
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse2004OrderShippingAddress } from './InlineResponse2004OrderShippingAddress';
import { InlineResponse200OrderMetadata } from './InlineResponse200OrderMetadata';
import { Set } from './Set';
import { HttpFile } from '../http/http';

export class InlineResponse2004Order {
    'currency': string;
    'discounts': Set<any>;
    'items': Set<any>;
    'itemsTotalAmount': number;
    'metadata': InlineResponse200OrderMetadata;
    'orderId': string;
    'shippingAddress': InlineResponse2004OrderShippingAddress;
    'shippingAmount': number;
    'storeCode': string;
    'subTotal': number;
    'taxAmount': number;
    'totalAmount': number;
    'userInstructions': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "discounts",
            "baseName": "discounts",
            "type": "Set<any>",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Set<any>",
            "format": ""
        },
        {
            "name": "itemsTotalAmount",
            "baseName": "items_total_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "InlineResponse200OrderMetadata",
            "format": ""
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "shippingAddress",
            "baseName": "shipping_address",
            "type": "InlineResponse2004OrderShippingAddress",
            "format": ""
        },
        {
            "name": "shippingAmount",
            "baseName": "shipping_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "storeCode",
            "baseName": "store_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "subTotal",
            "baseName": "sub_total",
            "type": "number",
            "format": ""
        },
        {
            "name": "taxAmount",
            "baseName": "tax_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalAmount",
            "baseName": "total_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "userInstructions",
            "baseName": "user_instructions",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2004Order.attributeTypeMap;
    }

    public constructor() {
    }
}

