/**
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MerchantsOrdersOrderShippingOptionsDetailsContact {
    'name': string;
    'phone': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MerchantsOrdersOrderShippingOptionsDetailsContact.attributeTypeMap;
    }

    public constructor() {
    }
}

