/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import InlineObject from './model/InlineObject';
import InlineObject1 from './model/InlineObject1';
import InlineObject2 from './model/InlineObject2';
import InlineObject3 from './model/InlineObject3';
import InlineObject4 from './model/InlineObject4';
import InlineObject5 from './model/InlineObject5';
import InlineObject6 from './model/InlineObject6';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse2001Order from './model/InlineResponse2001Order';
import InlineResponse2001OrderMetadata from './model/InlineResponse2001OrderMetadata';
import InlineResponse2001OrderShippingAddress from './model/InlineResponse2001OrderShippingAddress';
import InlineResponse2001OrderShippingOptions from './model/InlineResponse2001OrderShippingOptions';
import InlineResponse2001OrderShippingOptionsDetails from './model/InlineResponse2001OrderShippingOptionsDetails';
import InlineResponse2001OrderShippingOptionsDetailsAdditionalDetails from './model/InlineResponse2001OrderShippingOptionsDetailsAdditionalDetails';
import InlineResponse2001OrderShippingOptionsDetailsAddressCoordinates from './model/InlineResponse2001OrderShippingOptionsDetailsAddressCoordinates';
import InlineResponse2001OrderShippingOptionsDetailsContact from './model/InlineResponse2001OrderShippingOptionsDetailsContact';
import InlineResponse2002 from './model/InlineResponse2002';
import InlineResponse2002Order from './model/InlineResponse2002Order';
import InlineResponse2002OrderShippingAddress from './model/InlineResponse2002OrderShippingAddress';
import InlineResponse2002OrderShippingOptions from './model/InlineResponse2002OrderShippingOptions';
import InlineResponse2002OrderShippingOptionsDetails from './model/InlineResponse2002OrderShippingOptionsDetails';
import InlineResponse2003 from './model/InlineResponse2003';
import InlineResponse2003Order from './model/InlineResponse2003Order';
import InlineResponse2003OrderShippingOptions from './model/InlineResponse2003OrderShippingOptions';
import InlineResponse2004 from './model/InlineResponse2004';
import InlineResponse2004Order from './model/InlineResponse2004Order';
import InlineResponse2004OrderShippingAddress from './model/InlineResponse2004OrderShippingAddress';
import InlineResponse2004ShippingOption from './model/InlineResponse2004ShippingOption';
import InlineResponse2005 from './model/InlineResponse2005';
import InlineResponse2006 from './model/InlineResponse2006';
import InlineResponse2007 from './model/InlineResponse2007';
import InlineResponse2007Order from './model/InlineResponse2007Order';
import InlineResponse2007OrderPayment from './model/InlineResponse2007OrderPayment';
import InlineResponse2007OrderPaymentData from './model/InlineResponse2007OrderPaymentData';
import InlineResponse2007OrderPaymentDataAmount from './model/InlineResponse2007OrderPaymentDataAmount';
import InlineResponse2007OrderPaymentDataCustomer from './model/InlineResponse2007OrderPaymentDataCustomer';
import InlineResponse2007OrderPaymentDataFromCard from './model/InlineResponse2007OrderPaymentDataFromCard';
import InlineResponse2007OrderPaymentDataMerchant from './model/InlineResponse2007OrderPaymentDataMerchant';
import InlineResponse2008 from './model/InlineResponse2008';
import InlineResponse2009 from './model/InlineResponse2009';
import InlineResponse200Order from './model/InlineResponse200Order';
import InlineResponse200OrderMetadata from './model/InlineResponse200OrderMetadata';
import InlineResponse200OrderShippingAddress from './model/InlineResponse200OrderShippingAddress';
import InlineResponse200OrderShippingOptions from './model/InlineResponse200OrderShippingOptions';
import InlineResponse200OrderShippingOptionsDetails from './model/InlineResponse200OrderShippingOptionsDetails';
import InlineResponse200OrderShippingOptionsDetailsAdditionalDetails from './model/InlineResponse200OrderShippingOptionsDetailsAdditionalDetails';
import InlineResponse200OrderShippingOptionsDetailsAddressCoordinates from './model/InlineResponse200OrderShippingOptionsDetailsAddressCoordinates';
import InlineResponse200OrderShippingOptionsDetailsContact from './model/InlineResponse200OrderShippingOptionsDetailsContact';
import MerchantsOrdersOrder from './model/MerchantsOrdersOrder';
import MerchantsOrdersOrderShippingAddress from './model/MerchantsOrdersOrderShippingAddress';
import MerchantsOrdersOrderShippingOptions from './model/MerchantsOrdersOrderShippingOptions';
import MerchantsOrdersOrderShippingOptionsDetails from './model/MerchantsOrdersOrderShippingOptionsDetails';
import MerchantsOrdersOrderShippingOptionsDetailsContact from './model/MerchantsOrdersOrderShippingOptionsDetailsContact';
import MerchantsTransactionsPurchaseCreditCard from './model/MerchantsTransactionsPurchaseCreditCard';
import MerchantsTransactionsPurchaseSpecificFields from './model/MerchantsTransactionsPurchaseSpecificFields';
import ExternalMerchantAPIApi from './api/ExternalMerchantAPIApi';
import UsersApi from './api/UsersApi';


/**
* API_Gateway.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ApiGateway = require('index'); // See note below*.
* var xxxSvc = new ApiGateway.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ApiGateway.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ApiGateway.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ApiGateway.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The InlineObject model constructor.
     * @property {module:model/InlineObject}
     */
    InlineObject,

    /**
     * The InlineObject1 model constructor.
     * @property {module:model/InlineObject1}
     */
    InlineObject1,

    /**
     * The InlineObject2 model constructor.
     * @property {module:model/InlineObject2}
     */
    InlineObject2,

    /**
     * The InlineObject3 model constructor.
     * @property {module:model/InlineObject3}
     */
    InlineObject3,

    /**
     * The InlineObject4 model constructor.
     * @property {module:model/InlineObject4}
     */
    InlineObject4,

    /**
     * The InlineObject5 model constructor.
     * @property {module:model/InlineObject5}
     */
    InlineObject5,

    /**
     * The InlineObject6 model constructor.
     * @property {module:model/InlineObject6}
     */
    InlineObject6,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse2001Order model constructor.
     * @property {module:model/InlineResponse2001Order}
     */
    InlineResponse2001Order,

    /**
     * The InlineResponse2001OrderMetadata model constructor.
     * @property {module:model/InlineResponse2001OrderMetadata}
     */
    InlineResponse2001OrderMetadata,

    /**
     * The InlineResponse2001OrderShippingAddress model constructor.
     * @property {module:model/InlineResponse2001OrderShippingAddress}
     */
    InlineResponse2001OrderShippingAddress,

    /**
     * The InlineResponse2001OrderShippingOptions model constructor.
     * @property {module:model/InlineResponse2001OrderShippingOptions}
     */
    InlineResponse2001OrderShippingOptions,

    /**
     * The InlineResponse2001OrderShippingOptionsDetails model constructor.
     * @property {module:model/InlineResponse2001OrderShippingOptionsDetails}
     */
    InlineResponse2001OrderShippingOptionsDetails,

    /**
     * The InlineResponse2001OrderShippingOptionsDetailsAdditionalDetails model constructor.
     * @property {module:model/InlineResponse2001OrderShippingOptionsDetailsAdditionalDetails}
     */
    InlineResponse2001OrderShippingOptionsDetailsAdditionalDetails,

    /**
     * The InlineResponse2001OrderShippingOptionsDetailsAddressCoordinates model constructor.
     * @property {module:model/InlineResponse2001OrderShippingOptionsDetailsAddressCoordinates}
     */
    InlineResponse2001OrderShippingOptionsDetailsAddressCoordinates,

    /**
     * The InlineResponse2001OrderShippingOptionsDetailsContact model constructor.
     * @property {module:model/InlineResponse2001OrderShippingOptionsDetailsContact}
     */
    InlineResponse2001OrderShippingOptionsDetailsContact,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2002Order model constructor.
     * @property {module:model/InlineResponse2002Order}
     */
    InlineResponse2002Order,

    /**
     * The InlineResponse2002OrderShippingAddress model constructor.
     * @property {module:model/InlineResponse2002OrderShippingAddress}
     */
    InlineResponse2002OrderShippingAddress,

    /**
     * The InlineResponse2002OrderShippingOptions model constructor.
     * @property {module:model/InlineResponse2002OrderShippingOptions}
     */
    InlineResponse2002OrderShippingOptions,

    /**
     * The InlineResponse2002OrderShippingOptionsDetails model constructor.
     * @property {module:model/InlineResponse2002OrderShippingOptionsDetails}
     */
    InlineResponse2002OrderShippingOptionsDetails,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse2003Order model constructor.
     * @property {module:model/InlineResponse2003Order}
     */
    InlineResponse2003Order,

    /**
     * The InlineResponse2003OrderShippingOptions model constructor.
     * @property {module:model/InlineResponse2003OrderShippingOptions}
     */
    InlineResponse2003OrderShippingOptions,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse2004Order model constructor.
     * @property {module:model/InlineResponse2004Order}
     */
    InlineResponse2004Order,

    /**
     * The InlineResponse2004OrderShippingAddress model constructor.
     * @property {module:model/InlineResponse2004OrderShippingAddress}
     */
    InlineResponse2004OrderShippingAddress,

    /**
     * The InlineResponse2004ShippingOption model constructor.
     * @property {module:model/InlineResponse2004ShippingOption}
     */
    InlineResponse2004ShippingOption,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:model/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The InlineResponse2006 model constructor.
     * @property {module:model/InlineResponse2006}
     */
    InlineResponse2006,

    /**
     * The InlineResponse2007 model constructor.
     * @property {module:model/InlineResponse2007}
     */
    InlineResponse2007,

    /**
     * The InlineResponse2007Order model constructor.
     * @property {module:model/InlineResponse2007Order}
     */
    InlineResponse2007Order,

    /**
     * The InlineResponse2007OrderPayment model constructor.
     * @property {module:model/InlineResponse2007OrderPayment}
     */
    InlineResponse2007OrderPayment,

    /**
     * The InlineResponse2007OrderPaymentData model constructor.
     * @property {module:model/InlineResponse2007OrderPaymentData}
     */
    InlineResponse2007OrderPaymentData,

    /**
     * The InlineResponse2007OrderPaymentDataAmount model constructor.
     * @property {module:model/InlineResponse2007OrderPaymentDataAmount}
     */
    InlineResponse2007OrderPaymentDataAmount,

    /**
     * The InlineResponse2007OrderPaymentDataCustomer model constructor.
     * @property {module:model/InlineResponse2007OrderPaymentDataCustomer}
     */
    InlineResponse2007OrderPaymentDataCustomer,

    /**
     * The InlineResponse2007OrderPaymentDataFromCard model constructor.
     * @property {module:model/InlineResponse2007OrderPaymentDataFromCard}
     */
    InlineResponse2007OrderPaymentDataFromCard,

    /**
     * The InlineResponse2007OrderPaymentDataMerchant model constructor.
     * @property {module:model/InlineResponse2007OrderPaymentDataMerchant}
     */
    InlineResponse2007OrderPaymentDataMerchant,

    /**
     * The InlineResponse2008 model constructor.
     * @property {module:model/InlineResponse2008}
     */
    InlineResponse2008,

    /**
     * The InlineResponse2009 model constructor.
     * @property {module:model/InlineResponse2009}
     */
    InlineResponse2009,

    /**
     * The InlineResponse200Order model constructor.
     * @property {module:model/InlineResponse200Order}
     */
    InlineResponse200Order,

    /**
     * The InlineResponse200OrderMetadata model constructor.
     * @property {module:model/InlineResponse200OrderMetadata}
     */
    InlineResponse200OrderMetadata,

    /**
     * The InlineResponse200OrderShippingAddress model constructor.
     * @property {module:model/InlineResponse200OrderShippingAddress}
     */
    InlineResponse200OrderShippingAddress,

    /**
     * The InlineResponse200OrderShippingOptions model constructor.
     * @property {module:model/InlineResponse200OrderShippingOptions}
     */
    InlineResponse200OrderShippingOptions,

    /**
     * The InlineResponse200OrderShippingOptionsDetails model constructor.
     * @property {module:model/InlineResponse200OrderShippingOptionsDetails}
     */
    InlineResponse200OrderShippingOptionsDetails,

    /**
     * The InlineResponse200OrderShippingOptionsDetailsAdditionalDetails model constructor.
     * @property {module:model/InlineResponse200OrderShippingOptionsDetailsAdditionalDetails}
     */
    InlineResponse200OrderShippingOptionsDetailsAdditionalDetails,

    /**
     * The InlineResponse200OrderShippingOptionsDetailsAddressCoordinates model constructor.
     * @property {module:model/InlineResponse200OrderShippingOptionsDetailsAddressCoordinates}
     */
    InlineResponse200OrderShippingOptionsDetailsAddressCoordinates,

    /**
     * The InlineResponse200OrderShippingOptionsDetailsContact model constructor.
     * @property {module:model/InlineResponse200OrderShippingOptionsDetailsContact}
     */
    InlineResponse200OrderShippingOptionsDetailsContact,

    /**
     * The MerchantsOrdersOrder model constructor.
     * @property {module:model/MerchantsOrdersOrder}
     */
    MerchantsOrdersOrder,

    /**
     * The MerchantsOrdersOrderShippingAddress model constructor.
     * @property {module:model/MerchantsOrdersOrderShippingAddress}
     */
    MerchantsOrdersOrderShippingAddress,

    /**
     * The MerchantsOrdersOrderShippingOptions model constructor.
     * @property {module:model/MerchantsOrdersOrderShippingOptions}
     */
    MerchantsOrdersOrderShippingOptions,

    /**
     * The MerchantsOrdersOrderShippingOptionsDetails model constructor.
     * @property {module:model/MerchantsOrdersOrderShippingOptionsDetails}
     */
    MerchantsOrdersOrderShippingOptionsDetails,

    /**
     * The MerchantsOrdersOrderShippingOptionsDetailsContact model constructor.
     * @property {module:model/MerchantsOrdersOrderShippingOptionsDetailsContact}
     */
    MerchantsOrdersOrderShippingOptionsDetailsContact,

    /**
     * The MerchantsTransactionsPurchaseCreditCard model constructor.
     * @property {module:model/MerchantsTransactionsPurchaseCreditCard}
     */
    MerchantsTransactionsPurchaseCreditCard,

    /**
     * The MerchantsTransactionsPurchaseSpecificFields model constructor.
     * @property {module:model/MerchantsTransactionsPurchaseSpecificFields}
     */
    MerchantsTransactionsPurchaseSpecificFields,

    /**
    * The ExternalMerchantAPIApi service constructor.
    * @property {module:api/ExternalMerchantAPIApi}
    */
    ExternalMerchantAPIApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
