/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse200OrderMetadata model module.
 * @module model/InlineResponse200OrderMetadata
 * @version 1.0
 */
class InlineResponse200OrderMetadata {
    /**
     * Constructs a new <code>InlineResponse200OrderMetadata</code>.
     * @alias module:model/InlineResponse200OrderMetadata
     * @param key1 {String} 
     * @param key2 {String} 
     */
    constructor(key1, key2) { 
        
        InlineResponse200OrderMetadata.initialize(this, key1, key2);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, key1, key2) { 
        obj['key1'] = key1;
        obj['key2'] = key2;
    }

    /**
     * Constructs a <code>InlineResponse200OrderMetadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse200OrderMetadata} obj Optional instance to populate.
     * @return {module:model/InlineResponse200OrderMetadata} The populated <code>InlineResponse200OrderMetadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200OrderMetadata();

            if (data.hasOwnProperty('key1')) {
                obj['key1'] = ApiClient.convertToType(data['key1'], 'String');
            }
            if (data.hasOwnProperty('key2')) {
                obj['key2'] = ApiClient.convertToType(data['key2'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} key1
 */
InlineResponse200OrderMetadata.prototype['key1'] = undefined;

/**
 * @member {String} key2
 */
InlineResponse200OrderMetadata.prototype['key2'] = undefined;






export default InlineResponse200OrderMetadata;

