/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2007OrderPaymentDataCustomer model module.
 * @module model/InlineResponse2007OrderPaymentDataCustomer
 * @version 1.0
 */
class InlineResponse2007OrderPaymentDataCustomer {
    /**
     * Constructs a new <code>InlineResponse2007OrderPaymentDataCustomer</code>.
     * @alias module:model/InlineResponse2007OrderPaymentDataCustomer
     * @param email {String} 
     * @param id {String} 
     */
    constructor(email, id) { 
        
        InlineResponse2007OrderPaymentDataCustomer.initialize(this, email, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, id) { 
        obj['email'] = email;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>InlineResponse2007OrderPaymentDataCustomer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2007OrderPaymentDataCustomer} obj Optional instance to populate.
     * @return {module:model/InlineResponse2007OrderPaymentDataCustomer} The populated <code>InlineResponse2007OrderPaymentDataCustomer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2007OrderPaymentDataCustomer();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} email
 */
InlineResponse2007OrderPaymentDataCustomer.prototype['email'] = undefined;

/**
 * @member {String} id
 */
InlineResponse2007OrderPaymentDataCustomer.prototype['id'] = undefined;






export default InlineResponse2007OrderPaymentDataCustomer;

