/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2007OrderPaymentDataAmount model module.
 * @module model/InlineResponse2007OrderPaymentDataAmount
 * @version 1.0
 */
class InlineResponse2007OrderPaymentDataAmount {
    /**
     * Constructs a new <code>InlineResponse2007OrderPaymentDataAmount</code>.
     * @alias module:model/InlineResponse2007OrderPaymentDataAmount
     * @param amount {Number} 
     * @param currency {String} 
     */
    constructor(amount, currency) { 
        
        InlineResponse2007OrderPaymentDataAmount.initialize(this, amount, currency);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, currency) { 
        obj['amount'] = amount;
        obj['currency'] = currency;
    }

    /**
     * Constructs a <code>InlineResponse2007OrderPaymentDataAmount</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2007OrderPaymentDataAmount} obj Optional instance to populate.
     * @return {module:model/InlineResponse2007OrderPaymentDataAmount} The populated <code>InlineResponse2007OrderPaymentDataAmount</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2007OrderPaymentDataAmount();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} amount
 */
InlineResponse2007OrderPaymentDataAmount.prototype['amount'] = undefined;

/**
 * @member {String} currency
 */
InlineResponse2007OrderPaymentDataAmount.prototype['currency'] = undefined;






export default InlineResponse2007OrderPaymentDataAmount;

