/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2002OrderShippingAddress model module.
 * @module model/InlineResponse2002OrderShippingAddress
 * @version 1.0
 */
class InlineResponse2002OrderShippingAddress {
    /**
     * Constructs a new <code>InlineResponse2002OrderShippingAddress</code>.
     * @alias module:model/InlineResponse2002OrderShippingAddress
     */
    constructor() { 
        
        InlineResponse2002OrderShippingAddress.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2002OrderShippingAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2002OrderShippingAddress} obj Optional instance to populate.
     * @return {module:model/InlineResponse2002OrderShippingAddress} The populated <code>InlineResponse2002OrderShippingAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2002OrderShippingAddress();

            if (data.hasOwnProperty('additional_description')) {
                obj['additional_description'] = ApiClient.convertToType(data['additional_description'], 'String');
            }
            if (data.hasOwnProperty('address1')) {
                obj['address1'] = ApiClient.convertToType(data['address1'], 'String');
            }
            if (data.hasOwnProperty('address2')) {
                obj['address2'] = ApiClient.convertToType(data['address2'], 'String');
            }
            if (data.hasOwnProperty('address_type')) {
                obj['address_type'] = ApiClient.convertToType(data['address_type'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('country_code')) {
                obj['country_code'] = ApiClient.convertToType(data['country_code'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('identity_document')) {
                obj['identity_document'] = ApiClient.convertToType(data['identity_document'], 'String');
            }
            if (data.hasOwnProperty('is_default')) {
                obj['is_default'] = ApiClient.convertToType(data['is_default'], 'Boolean');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('lat')) {
                obj['lat'] = ApiClient.convertToType(data['lat'], 'Number');
            }
            if (data.hasOwnProperty('lng')) {
                obj['lng'] = ApiClient.convertToType(data['lng'], 'Number');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('state_name')) {
                obj['state_name'] = ApiClient.convertToType(data['state_name'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('zipcode')) {
                obj['zipcode'] = ApiClient.convertToType(data['zipcode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} additional_description
 */
InlineResponse2002OrderShippingAddress.prototype['additional_description'] = undefined;

/**
 * @member {String} address1
 */
InlineResponse2002OrderShippingAddress.prototype['address1'] = undefined;

/**
 * @member {String} address2
 */
InlineResponse2002OrderShippingAddress.prototype['address2'] = undefined;

/**
 * @member {String} address_type
 */
InlineResponse2002OrderShippingAddress.prototype['address_type'] = undefined;

/**
 * @member {String} city
 */
InlineResponse2002OrderShippingAddress.prototype['city'] = undefined;

/**
 * @member {String} country_code
 */
InlineResponse2002OrderShippingAddress.prototype['country_code'] = undefined;

/**
 * @member {String} created_at
 */
InlineResponse2002OrderShippingAddress.prototype['created_at'] = undefined;

/**
 * @member {String} first_name
 */
InlineResponse2002OrderShippingAddress.prototype['first_name'] = undefined;

/**
 * @member {Number} id
 */
InlineResponse2002OrderShippingAddress.prototype['id'] = undefined;

/**
 * @member {String} identity_document
 */
InlineResponse2002OrderShippingAddress.prototype['identity_document'] = undefined;

/**
 * @member {Boolean} is_default
 */
InlineResponse2002OrderShippingAddress.prototype['is_default'] = undefined;

/**
 * @member {String} last_name
 */
InlineResponse2002OrderShippingAddress.prototype['last_name'] = undefined;

/**
 * @member {Number} lat
 */
InlineResponse2002OrderShippingAddress.prototype['lat'] = undefined;

/**
 * @member {Number} lng
 */
InlineResponse2002OrderShippingAddress.prototype['lng'] = undefined;

/**
 * @member {String} phone
 */
InlineResponse2002OrderShippingAddress.prototype['phone'] = undefined;

/**
 * @member {String} state_name
 */
InlineResponse2002OrderShippingAddress.prototype['state_name'] = undefined;

/**
 * @member {String} updated_at
 */
InlineResponse2002OrderShippingAddress.prototype['updated_at'] = undefined;

/**
 * @member {String} user_id
 */
InlineResponse2002OrderShippingAddress.prototype['user_id'] = undefined;

/**
 * @member {String} zipcode
 */
InlineResponse2002OrderShippingAddress.prototype['zipcode'] = undefined;






export default InlineResponse2002OrderShippingAddress;

