/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2001OrderMetadata model module.
 * @module model/InlineResponse2001OrderMetadata
 * @version 1.0
 */
class InlineResponse2001OrderMetadata {
    /**
     * Constructs a new <code>InlineResponse2001OrderMetadata</code>.
     * @alias module:model/InlineResponse2001OrderMetadata
     */
    constructor() { 
        
        InlineResponse2001OrderMetadata.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2001OrderMetadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2001OrderMetadata} obj Optional instance to populate.
     * @return {module:model/InlineResponse2001OrderMetadata} The populated <code>InlineResponse2001OrderMetadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2001OrderMetadata();

            if (data.hasOwnProperty('key1')) {
                obj['key1'] = ApiClient.convertToType(data['key1'], 'String');
            }
            if (data.hasOwnProperty('key2')) {
                obj['key2'] = ApiClient.convertToType(data['key2'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} key1
 */
InlineResponse2001OrderMetadata.prototype['key1'] = undefined;

/**
 * @member {String} key2
 */
InlineResponse2001OrderMetadata.prototype['key2'] = undefined;






export default InlineResponse2001OrderMetadata;

