/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse200OrderShippingOptionsDetailsAddressCoordinates model module.
 * @module model/InlineResponse200OrderShippingOptionsDetailsAddressCoordinates
 * @version 1.0
 */
class InlineResponse200OrderShippingOptionsDetailsAddressCoordinates {
    /**
     * Constructs a new <code>InlineResponse200OrderShippingOptionsDetailsAddressCoordinates</code>.
     * @alias module:model/InlineResponse200OrderShippingOptionsDetailsAddressCoordinates
     * @param lat {Number} 
     * @param lng {Number} 
     */
    constructor(lat, lng) { 
        
        InlineResponse200OrderShippingOptionsDetailsAddressCoordinates.initialize(this, lat, lng);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, lat, lng) { 
        obj['lat'] = lat;
        obj['lng'] = lng;
    }

    /**
     * Constructs a <code>InlineResponse200OrderShippingOptionsDetailsAddressCoordinates</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse200OrderShippingOptionsDetailsAddressCoordinates} obj Optional instance to populate.
     * @return {module:model/InlineResponse200OrderShippingOptionsDetailsAddressCoordinates} The populated <code>InlineResponse200OrderShippingOptionsDetailsAddressCoordinates</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200OrderShippingOptionsDetailsAddressCoordinates();

            if (data.hasOwnProperty('lat')) {
                obj['lat'] = ApiClient.convertToType(data['lat'], 'Number');
            }
            if (data.hasOwnProperty('lng')) {
                obj['lng'] = ApiClient.convertToType(data['lng'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} lat
 */
InlineResponse200OrderShippingOptionsDetailsAddressCoordinates.prototype['lat'] = undefined;

/**
 * @member {Number} lng
 */
InlineResponse200OrderShippingOptionsDetailsAddressCoordinates.prototype['lng'] = undefined;






export default InlineResponse200OrderShippingOptionsDetailsAddressCoordinates;

