/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MerchantsOrdersOrderShippingAddress model module.
 * @module model/MerchantsOrdersOrderShippingAddress
 * @version 1.0
 */
class MerchantsOrdersOrderShippingAddress {
    /**
     * Constructs a new <code>MerchantsOrdersOrderShippingAddress</code>.
     * @alias module:model/MerchantsOrdersOrderShippingAddress
     * @param additionalDescription {String} 
     * @param address1 {String} 
     * @param address2 {String} 
     * @param addressType {String} 
     * @param city {String} 
     * @param country {String} 
     * @param createdAt {String} 
     * @param firstName {String} 
     * @param id {Number} 
     * @param identityDocument {String} 
     * @param isDefault {Boolean} 
     * @param lastName {String} 
     * @param lat {Number} 
     * @param lng {Number} 
     * @param phone {String} 
     * @param stateName {String} 
     * @param updatedAt {String} 
     * @param userId {String} 
     * @param zipcode {String} 
     */
    constructor(additionalDescription, address1, address2, addressType, city, country, createdAt, firstName, id, identityDocument, isDefault, lastName, lat, lng, phone, stateName, updatedAt, userId, zipcode) { 
        
        MerchantsOrdersOrderShippingAddress.initialize(this, additionalDescription, address1, address2, addressType, city, country, createdAt, firstName, id, identityDocument, isDefault, lastName, lat, lng, phone, stateName, updatedAt, userId, zipcode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, additionalDescription, address1, address2, addressType, city, country, createdAt, firstName, id, identityDocument, isDefault, lastName, lat, lng, phone, stateName, updatedAt, userId, zipcode) { 
        obj['additional_description'] = additionalDescription;
        obj['address1'] = address1;
        obj['address2'] = address2;
        obj['address_type'] = addressType;
        obj['city'] = city;
        obj['country'] = country;
        obj['created_at'] = createdAt;
        obj['first_name'] = firstName;
        obj['id'] = id;
        obj['identity_document'] = identityDocument;
        obj['is_default'] = isDefault;
        obj['last_name'] = lastName;
        obj['lat'] = lat;
        obj['lng'] = lng;
        obj['phone'] = phone;
        obj['state_name'] = stateName;
        obj['updated_at'] = updatedAt;
        obj['user_id'] = userId;
        obj['zipcode'] = zipcode;
    }

    /**
     * Constructs a <code>MerchantsOrdersOrderShippingAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantsOrdersOrderShippingAddress} obj Optional instance to populate.
     * @return {module:model/MerchantsOrdersOrderShippingAddress} The populated <code>MerchantsOrdersOrderShippingAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantsOrdersOrderShippingAddress();

            if (data.hasOwnProperty('additional_description')) {
                obj['additional_description'] = ApiClient.convertToType(data['additional_description'], 'String');
            }
            if (data.hasOwnProperty('address1')) {
                obj['address1'] = ApiClient.convertToType(data['address1'], 'String');
            }
            if (data.hasOwnProperty('address2')) {
                obj['address2'] = ApiClient.convertToType(data['address2'], 'String');
            }
            if (data.hasOwnProperty('address_type')) {
                obj['address_type'] = ApiClient.convertToType(data['address_type'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('identity_document')) {
                obj['identity_document'] = ApiClient.convertToType(data['identity_document'], 'String');
            }
            if (data.hasOwnProperty('is_default')) {
                obj['is_default'] = ApiClient.convertToType(data['is_default'], 'Boolean');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('lat')) {
                obj['lat'] = ApiClient.convertToType(data['lat'], 'Number');
            }
            if (data.hasOwnProperty('lng')) {
                obj['lng'] = ApiClient.convertToType(data['lng'], 'Number');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('state_name')) {
                obj['state_name'] = ApiClient.convertToType(data['state_name'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('zipcode')) {
                obj['zipcode'] = ApiClient.convertToType(data['zipcode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} additional_description
 */
MerchantsOrdersOrderShippingAddress.prototype['additional_description'] = undefined;

/**
 * @member {String} address1
 */
MerchantsOrdersOrderShippingAddress.prototype['address1'] = undefined;

/**
 * @member {String} address2
 */
MerchantsOrdersOrderShippingAddress.prototype['address2'] = undefined;

/**
 * @member {String} address_type
 */
MerchantsOrdersOrderShippingAddress.prototype['address_type'] = undefined;

/**
 * @member {String} city
 */
MerchantsOrdersOrderShippingAddress.prototype['city'] = undefined;

/**
 * @member {String} country
 */
MerchantsOrdersOrderShippingAddress.prototype['country'] = undefined;

/**
 * @member {String} created_at
 */
MerchantsOrdersOrderShippingAddress.prototype['created_at'] = undefined;

/**
 * @member {String} first_name
 */
MerchantsOrdersOrderShippingAddress.prototype['first_name'] = undefined;

/**
 * @member {Number} id
 */
MerchantsOrdersOrderShippingAddress.prototype['id'] = undefined;

/**
 * @member {String} identity_document
 */
MerchantsOrdersOrderShippingAddress.prototype['identity_document'] = undefined;

/**
 * @member {Boolean} is_default
 */
MerchantsOrdersOrderShippingAddress.prototype['is_default'] = undefined;

/**
 * @member {String} last_name
 */
MerchantsOrdersOrderShippingAddress.prototype['last_name'] = undefined;

/**
 * @member {Number} lat
 */
MerchantsOrdersOrderShippingAddress.prototype['lat'] = undefined;

/**
 * @member {Number} lng
 */
MerchantsOrdersOrderShippingAddress.prototype['lng'] = undefined;

/**
 * @member {String} phone
 */
MerchantsOrdersOrderShippingAddress.prototype['phone'] = undefined;

/**
 * @member {String} state_name
 */
MerchantsOrdersOrderShippingAddress.prototype['state_name'] = undefined;

/**
 * @member {String} updated_at
 */
MerchantsOrdersOrderShippingAddress.prototype['updated_at'] = undefined;

/**
 * @member {String} user_id
 */
MerchantsOrdersOrderShippingAddress.prototype['user_id'] = undefined;

/**
 * @member {String} zipcode
 */
MerchantsOrdersOrderShippingAddress.prototype['zipcode'] = undefined;






export default MerchantsOrdersOrderShippingAddress;

