/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MerchantsOrdersOrderShippingOptionsDetailsContact model module.
 * @module model/MerchantsOrdersOrderShippingOptionsDetailsContact
 * @version 1.0
 */
class MerchantsOrdersOrderShippingOptionsDetailsContact {
    /**
     * Constructs a new <code>MerchantsOrdersOrderShippingOptionsDetailsContact</code>.
     * @alias module:model/MerchantsOrdersOrderShippingOptionsDetailsContact
     * @param name {String} 
     * @param phone {Number} 
     */
    constructor(name, phone) { 
        
        MerchantsOrdersOrderShippingOptionsDetailsContact.initialize(this, name, phone);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, phone) { 
        obj['name'] = name;
        obj['phone'] = phone;
    }

    /**
     * Constructs a <code>MerchantsOrdersOrderShippingOptionsDetailsContact</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantsOrdersOrderShippingOptionsDetailsContact} obj Optional instance to populate.
     * @return {module:model/MerchantsOrdersOrderShippingOptionsDetailsContact} The populated <code>MerchantsOrdersOrderShippingOptionsDetailsContact</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantsOrdersOrderShippingOptionsDetailsContact();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
MerchantsOrdersOrderShippingOptionsDetailsContact.prototype['name'] = undefined;

/**
 * @member {Number} phone
 */
MerchantsOrdersOrderShippingOptionsDetailsContact.prototype['phone'] = undefined;






export default MerchantsOrdersOrderShippingOptionsDetailsContact;

