/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MerchantsTransactionsPurchaseSpecificFields model module.
 * @module model/MerchantsTransactionsPurchaseSpecificFields
 * @version 1.0
 */
class MerchantsTransactionsPurchaseSpecificFields {
    /**
     * Constructs a new <code>MerchantsTransactionsPurchaseSpecificFields</code>.
     * @alias module:model/MerchantsTransactionsPurchaseSpecificFields
     * @param financialInstitution {String} 
     */
    constructor(financialInstitution) { 
        
        MerchantsTransactionsPurchaseSpecificFields.initialize(this, financialInstitution);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, financialInstitution) { 
        obj['financial_institution'] = financialInstitution;
    }

    /**
     * Constructs a <code>MerchantsTransactionsPurchaseSpecificFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantsTransactionsPurchaseSpecificFields} obj Optional instance to populate.
     * @return {module:model/MerchantsTransactionsPurchaseSpecificFields} The populated <code>MerchantsTransactionsPurchaseSpecificFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantsTransactionsPurchaseSpecificFields();

            if (data.hasOwnProperty('financial_institution')) {
                obj['financial_institution'] = ApiClient.convertToType(data['financial_institution'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} financial_institution
 */
MerchantsTransactionsPurchaseSpecificFields.prototype['financial_institution'] = undefined;






export default MerchantsTransactionsPurchaseSpecificFields;

