/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiGateway);
  }
}(this, function(expect, ApiGateway) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiGateway.InlineResponse2009();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2009', function() {
    it('should create an instance of InlineResponse2009', function() {
      // uncomment below and update the code to test InlineResponse2009
      //var instance = new ApiGateway.InlineResponse2009();
      //expect(instance).to.be.a(ApiGateway.InlineResponse2009);
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new ApiGateway.InlineResponse2009();
      //expect(instance).to.be();
    });

    it('should have the property deletedAt (base name: "deleted_at")', function() {
      // uncomment below and update the code to test the property deletedAt
      //var instance = new ApiGateway.InlineResponse2009();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new ApiGateway.InlineResponse2009();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "first_name")', function() {
      // uncomment below and update the code to test the property firstName
      //var instance = new ApiGateway.InlineResponse2009();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ApiGateway.InlineResponse2009();
      //expect(instance).to.be();
    });

    it('should have the property identityProviders (base name: "identity_providers")', function() {
      // uncomment below and update the code to test the property identityProviders
      //var instance = new ApiGateway.InlineResponse2009();
      //expect(instance).to.be();
    });

    it('should have the property isGuest (base name: "is_guest")', function() {
      // uncomment below and update the code to test the property isGuest
      //var instance = new ApiGateway.InlineResponse2009();
      //expect(instance).to.be();
    });

    it('should have the property isPhoneVerified (base name: "is_phone_verified")', function() {
      // uncomment below and update the code to test the property isPhoneVerified
      //var instance = new ApiGateway.InlineResponse2009();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "last_name")', function() {
      // uncomment below and update the code to test the property lastName
      //var instance = new ApiGateway.InlineResponse2009();
      //expect(instance).to.be();
    });

    it('should have the property merchantId (base name: "merchant_id")', function() {
      // uncomment below and update the code to test the property merchantId
      //var instance = new ApiGateway.InlineResponse2009();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instance = new ApiGateway.InlineResponse2009();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new ApiGateway.InlineResponse2009();
      //expect(instance).to.be();
    });

  });

}));
