/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiGateway);
  }
}(this, function(expect, ApiGateway) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiGateway.InlineResponse2007OrderPaymentData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2007OrderPaymentData', function() {
    it('should create an instance of InlineResponse2007OrderPaymentData', function() {
      // uncomment below and update the code to test InlineResponse2007OrderPaymentData
      //var instance = new ApiGateway.InlineResponse2007OrderPaymentData();
      //expect(instance).to.be.a(ApiGateway.InlineResponse2007OrderPaymentData);
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new ApiGateway.InlineResponse2007OrderPaymentData();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new ApiGateway.InlineResponse2007OrderPaymentData();
      //expect(instance).to.be();
    });

    it('should have the property customer (base name: "customer")', function() {
      // uncomment below and update the code to test the property customer
      //var instance = new ApiGateway.InlineResponse2007OrderPaymentData();
      //expect(instance).to.be();
    });

    it('should have the property fromCard (base name: "from_card")', function() {
      // uncomment below and update the code to test the property fromCard
      //var instance = new ApiGateway.InlineResponse2007OrderPaymentData();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ApiGateway.InlineResponse2007OrderPaymentData();
      //expect(instance).to.be();
    });

    it('should have the property merchant (base name: "merchant")', function() {
      // uncomment below and update the code to test the property merchant
      //var instance = new ApiGateway.InlineResponse2007OrderPaymentData();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instance = new ApiGateway.InlineResponse2007OrderPaymentData();
      //expect(instance).to.be();
    });

    it('should have the property methodType (base name: "method_type")', function() {
      // uncomment below and update the code to test the property methodType
      //var instance = new ApiGateway.InlineResponse2007OrderPaymentData();
      //expect(instance).to.be();
    });

    it('should have the property processor (base name: "processor")', function() {
      // uncomment below and update the code to test the property processor
      //var instance = new ApiGateway.InlineResponse2007OrderPaymentData();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new ApiGateway.InlineResponse2007OrderPaymentData();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new ApiGateway.InlineResponse2007OrderPaymentData();
      //expect(instance).to.be();
    });

  });

}));
