/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiGateway);
  }
}(this, function(expect, ApiGateway) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2001OrderShippingAddress', function() {
    it('should create an instance of InlineResponse2001OrderShippingAddress', function() {
      // uncomment below and update the code to test InlineResponse2001OrderShippingAddress
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be.a(ApiGateway.InlineResponse2001OrderShippingAddress);
    });

    it('should have the property additionalDescription (base name: "additional_description")', function() {
      // uncomment below and update the code to test the property additionalDescription
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

    it('should have the property address1 (base name: "address1")', function() {
      // uncomment below and update the code to test the property address1
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

    it('should have the property address2 (base name: "address2")', function() {
      // uncomment below and update the code to test the property address2
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

    it('should have the property addressType (base name: "address_type")', function() {
      // uncomment below and update the code to test the property addressType
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

    it('should have the property countryCode (base name: "country_code")', function() {
      // uncomment below and update the code to test the property countryCode
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "first_name")', function() {
      // uncomment below and update the code to test the property firstName
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

    it('should have the property identityDocument (base name: "identity_document")', function() {
      // uncomment below and update the code to test the property identityDocument
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

    it('should have the property isDefault (base name: "is_default")', function() {
      // uncomment below and update the code to test the property isDefault
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "last_name")', function() {
      // uncomment below and update the code to test the property lastName
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

    it('should have the property lat (base name: "lat")', function() {
      // uncomment below and update the code to test the property lat
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

    it('should have the property lng (base name: "lng")', function() {
      // uncomment below and update the code to test the property lng
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

    it('should have the property stateName (base name: "state_name")', function() {
      // uncomment below and update the code to test the property stateName
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

    it('should have the property zipcode (base name: "zipcode")', function() {
      // uncomment below and update the code to test the property zipcode
      //var instance = new ApiGateway.InlineResponse2001OrderShippingAddress();
      //expect(instance).to.be();
    });

  });

}));
