/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse2007OrderPayment from './InlineResponse2007OrderPayment';
import InlineResponse200OrderMetadata from './InlineResponse200OrderMetadata';
import InlineResponse200OrderShippingAddress from './InlineResponse200OrderShippingAddress';

/**
 * The InlineResponse2007Order model module.
 * @module model/InlineResponse2007Order
 * @version 1.0
 */
class InlineResponse2007Order {
    /**
     * Constructs a new <code>InlineResponse2007Order</code>.
     * @alias module:model/InlineResponse2007Order
     * @param currency {String} 
     * @param discounts {Array.<Object>} 
     * @param displayItemsTotalAmount {String} 
     * @param displayShippingAmount {String} 
     * @param displaySubTotal {String} 
     * @param displayTaxAmount {String} 
     * @param displayTotalAmount {String} 
     * @param items {Array.<Object>} 
     * @param itemsTotalAmount {Number} 
     * @param metadata {module:model/InlineResponse200OrderMetadata} 
     * @param orderId {String} 
     * @param payment {module:model/InlineResponse2007OrderPayment} 
     * @param shippingAddress {module:model/InlineResponse200OrderShippingAddress} 
     * @param shippingAmount {Number} 
     * @param status {String} 
     * @param storeCode {String} 
     * @param subTotal {Number} 
     * @param taxAmount {Number} 
     * @param totalAmount {Number} 
     * @param userInstructions {String} 
     */
    constructor(currency, discounts, displayItemsTotalAmount, displayShippingAmount, displaySubTotal, displayTaxAmount, displayTotalAmount, items, itemsTotalAmount, metadata, orderId, payment, shippingAddress, shippingAmount, status, storeCode, subTotal, taxAmount, totalAmount, userInstructions) { 
        
        InlineResponse2007Order.initialize(this, currency, discounts, displayItemsTotalAmount, displayShippingAmount, displaySubTotal, displayTaxAmount, displayTotalAmount, items, itemsTotalAmount, metadata, orderId, payment, shippingAddress, shippingAmount, status, storeCode, subTotal, taxAmount, totalAmount, userInstructions);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, currency, discounts, displayItemsTotalAmount, displayShippingAmount, displaySubTotal, displayTaxAmount, displayTotalAmount, items, itemsTotalAmount, metadata, orderId, payment, shippingAddress, shippingAmount, status, storeCode, subTotal, taxAmount, totalAmount, userInstructions) { 
        obj['currency'] = currency;
        obj['discounts'] = discounts;
        obj['display_items_total_amount'] = displayItemsTotalAmount;
        obj['display_shipping_amount'] = displayShippingAmount;
        obj['display_sub_total'] = displaySubTotal;
        obj['display_tax_amount'] = displayTaxAmount;
        obj['display_total_amount'] = displayTotalAmount;
        obj['items'] = items;
        obj['items_total_amount'] = itemsTotalAmount;
        obj['metadata'] = metadata;
        obj['order_id'] = orderId;
        obj['payment'] = payment;
        obj['shipping_address'] = shippingAddress;
        obj['shipping_amount'] = shippingAmount;
        obj['status'] = status;
        obj['store_code'] = storeCode;
        obj['sub_total'] = subTotal;
        obj['tax_amount'] = taxAmount;
        obj['total_amount'] = totalAmount;
        obj['user_instructions'] = userInstructions;
    }

    /**
     * Constructs a <code>InlineResponse2007Order</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2007Order} obj Optional instance to populate.
     * @return {module:model/InlineResponse2007Order} The populated <code>InlineResponse2007Order</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2007Order();

            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('discounts')) {
                obj['discounts'] = ApiClient.convertToType(data['discounts'], [Object]);
            }
            if (data.hasOwnProperty('display_items_total_amount')) {
                obj['display_items_total_amount'] = ApiClient.convertToType(data['display_items_total_amount'], 'String');
            }
            if (data.hasOwnProperty('display_shipping_amount')) {
                obj['display_shipping_amount'] = ApiClient.convertToType(data['display_shipping_amount'], 'String');
            }
            if (data.hasOwnProperty('display_sub_total')) {
                obj['display_sub_total'] = ApiClient.convertToType(data['display_sub_total'], 'String');
            }
            if (data.hasOwnProperty('display_tax_amount')) {
                obj['display_tax_amount'] = ApiClient.convertToType(data['display_tax_amount'], 'String');
            }
            if (data.hasOwnProperty('display_total_amount')) {
                obj['display_total_amount'] = ApiClient.convertToType(data['display_total_amount'], 'String');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [Object]);
            }
            if (data.hasOwnProperty('items_total_amount')) {
                obj['items_total_amount'] = ApiClient.convertToType(data['items_total_amount'], 'Number');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = InlineResponse200OrderMetadata.constructFromObject(data['metadata']);
            }
            if (data.hasOwnProperty('order_id')) {
                obj['order_id'] = ApiClient.convertToType(data['order_id'], 'String');
            }
            if (data.hasOwnProperty('payment')) {
                obj['payment'] = InlineResponse2007OrderPayment.constructFromObject(data['payment']);
            }
            if (data.hasOwnProperty('shipping_address')) {
                obj['shipping_address'] = InlineResponse200OrderShippingAddress.constructFromObject(data['shipping_address']);
            }
            if (data.hasOwnProperty('shipping_amount')) {
                obj['shipping_amount'] = ApiClient.convertToType(data['shipping_amount'], 'Number');
            }
            if (data.hasOwnProperty('shipping_options')) {
                obj['shipping_options'] = ApiClient.convertToType(data['shipping_options'], Object);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('store_code')) {
                obj['store_code'] = ApiClient.convertToType(data['store_code'], 'String');
            }
            if (data.hasOwnProperty('sub_total')) {
                obj['sub_total'] = ApiClient.convertToType(data['sub_total'], 'Number');
            }
            if (data.hasOwnProperty('tax_amount')) {
                obj['tax_amount'] = ApiClient.convertToType(data['tax_amount'], 'Number');
            }
            if (data.hasOwnProperty('total_amount')) {
                obj['total_amount'] = ApiClient.convertToType(data['total_amount'], 'Number');
            }
            if (data.hasOwnProperty('user_instructions')) {
                obj['user_instructions'] = ApiClient.convertToType(data['user_instructions'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} currency
 */
InlineResponse2007Order.prototype['currency'] = undefined;

/**
 * @member {Array.<Object>} discounts
 */
InlineResponse2007Order.prototype['discounts'] = undefined;

/**
 * @member {String} display_items_total_amount
 */
InlineResponse2007Order.prototype['display_items_total_amount'] = undefined;

/**
 * @member {String} display_shipping_amount
 */
InlineResponse2007Order.prototype['display_shipping_amount'] = undefined;

/**
 * @member {String} display_sub_total
 */
InlineResponse2007Order.prototype['display_sub_total'] = undefined;

/**
 * @member {String} display_tax_amount
 */
InlineResponse2007Order.prototype['display_tax_amount'] = undefined;

/**
 * @member {String} display_total_amount
 */
InlineResponse2007Order.prototype['display_total_amount'] = undefined;

/**
 * @member {Array.<Object>} items
 */
InlineResponse2007Order.prototype['items'] = undefined;

/**
 * @member {Number} items_total_amount
 */
InlineResponse2007Order.prototype['items_total_amount'] = undefined;

/**
 * @member {module:model/InlineResponse200OrderMetadata} metadata
 */
InlineResponse2007Order.prototype['metadata'] = undefined;

/**
 * @member {String} order_id
 */
InlineResponse2007Order.prototype['order_id'] = undefined;

/**
 * @member {module:model/InlineResponse2007OrderPayment} payment
 */
InlineResponse2007Order.prototype['payment'] = undefined;

/**
 * @member {module:model/InlineResponse200OrderShippingAddress} shipping_address
 */
InlineResponse2007Order.prototype['shipping_address'] = undefined;

/**
 * @member {Number} shipping_amount
 */
InlineResponse2007Order.prototype['shipping_amount'] = undefined;

/**
 * @member {Object} shipping_options
 */
InlineResponse2007Order.prototype['shipping_options'] = undefined;

/**
 * @member {String} status
 */
InlineResponse2007Order.prototype['status'] = undefined;

/**
 * @member {String} store_code
 */
InlineResponse2007Order.prototype['store_code'] = undefined;

/**
 * @member {Number} sub_total
 */
InlineResponse2007Order.prototype['sub_total'] = undefined;

/**
 * @member {Number} tax_amount
 */
InlineResponse2007Order.prototype['tax_amount'] = undefined;

/**
 * @member {Number} total_amount
 */
InlineResponse2007Order.prototype['total_amount'] = undefined;

/**
 * @member {String} user_instructions
 */
InlineResponse2007Order.prototype['user_instructions'] = undefined;






export default InlineResponse2007Order;

