/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse2007OrderPaymentDataAmount from './InlineResponse2007OrderPaymentDataAmount';
import InlineResponse2007OrderPaymentDataCustomer from './InlineResponse2007OrderPaymentDataCustomer';
import InlineResponse2007OrderPaymentDataFromCard from './InlineResponse2007OrderPaymentDataFromCard';
import InlineResponse2007OrderPaymentDataMerchant from './InlineResponse2007OrderPaymentDataMerchant';

/**
 * The InlineResponse2007OrderPaymentData model module.
 * @module model/InlineResponse2007OrderPaymentData
 * @version 1.0
 */
class InlineResponse2007OrderPaymentData {
    /**
     * Constructs a new <code>InlineResponse2007OrderPaymentData</code>.
     * @alias module:model/InlineResponse2007OrderPaymentData
     * @param amount {module:model/InlineResponse2007OrderPaymentDataAmount} 
     * @param createdAt {String} 
     * @param customer {module:model/InlineResponse2007OrderPaymentDataCustomer} 
     * @param fromCard {module:model/InlineResponse2007OrderPaymentDataFromCard} 
     * @param id {String} 
     * @param merchant {module:model/InlineResponse2007OrderPaymentDataMerchant} 
     * @param methodType {String} 
     * @param processor {String} 
     * @param status {String} 
     * @param updatedAt {String} 
     */
    constructor(amount, createdAt, customer, fromCard, id, merchant, methodType, processor, status, updatedAt) { 
        
        InlineResponse2007OrderPaymentData.initialize(this, amount, createdAt, customer, fromCard, id, merchant, methodType, processor, status, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, createdAt, customer, fromCard, id, merchant, methodType, processor, status, updatedAt) { 
        obj['amount'] = amount;
        obj['created_at'] = createdAt;
        obj['customer'] = customer;
        obj['from_card'] = fromCard;
        obj['id'] = id;
        obj['merchant'] = merchant;
        obj['method_type'] = methodType;
        obj['processor'] = processor;
        obj['status'] = status;
        obj['updated_at'] = updatedAt;
    }

    /**
     * Constructs a <code>InlineResponse2007OrderPaymentData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2007OrderPaymentData} obj Optional instance to populate.
     * @return {module:model/InlineResponse2007OrderPaymentData} The populated <code>InlineResponse2007OrderPaymentData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2007OrderPaymentData();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = InlineResponse2007OrderPaymentDataAmount.constructFromObject(data['amount']);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('customer')) {
                obj['customer'] = InlineResponse2007OrderPaymentDataCustomer.constructFromObject(data['customer']);
            }
            if (data.hasOwnProperty('from_card')) {
                obj['from_card'] = InlineResponse2007OrderPaymentDataFromCard.constructFromObject(data['from_card']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('merchant')) {
                obj['merchant'] = InlineResponse2007OrderPaymentDataMerchant.constructFromObject(data['merchant']);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
            if (data.hasOwnProperty('method_type')) {
                obj['method_type'] = ApiClient.convertToType(data['method_type'], 'String');
            }
            if (data.hasOwnProperty('processor')) {
                obj['processor'] = ApiClient.convertToType(data['processor'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/InlineResponse2007OrderPaymentDataAmount} amount
 */
InlineResponse2007OrderPaymentData.prototype['amount'] = undefined;

/**
 * @member {String} created_at
 */
InlineResponse2007OrderPaymentData.prototype['created_at'] = undefined;

/**
 * @member {module:model/InlineResponse2007OrderPaymentDataCustomer} customer
 */
InlineResponse2007OrderPaymentData.prototype['customer'] = undefined;

/**
 * @member {module:model/InlineResponse2007OrderPaymentDataFromCard} from_card
 */
InlineResponse2007OrderPaymentData.prototype['from_card'] = undefined;

/**
 * @member {String} id
 */
InlineResponse2007OrderPaymentData.prototype['id'] = undefined;

/**
 * @member {module:model/InlineResponse2007OrderPaymentDataMerchant} merchant
 */
InlineResponse2007OrderPaymentData.prototype['merchant'] = undefined;

/**
 * @member {Object} metadata
 */
InlineResponse2007OrderPaymentData.prototype['metadata'] = undefined;

/**
 * @member {String} method_type
 */
InlineResponse2007OrderPaymentData.prototype['method_type'] = undefined;

/**
 * @member {String} processor
 */
InlineResponse2007OrderPaymentData.prototype['processor'] = undefined;

/**
 * @member {String} status
 */
InlineResponse2007OrderPaymentData.prototype['status'] = undefined;

/**
 * @member {String} updated_at
 */
InlineResponse2007OrderPaymentData.prototype['updated_at'] = undefined;






export default InlineResponse2007OrderPaymentData;

