/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2009 model module.
 * @module model/InlineResponse2009
 * @version 1.0
 */
class InlineResponse2009 {
    /**
     * Constructs a new <code>InlineResponse2009</code>.
     * @alias module:model/InlineResponse2009
     */
    constructor() { 
        
        InlineResponse2009.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2009</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2009} obj Optional instance to populate.
     * @return {module:model/InlineResponse2009} The populated <code>InlineResponse2009</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2009();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = ApiClient.convertToType(data['deleted_at'], Object);
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('identity_providers')) {
                obj['identity_providers'] = ApiClient.convertToType(data['identity_providers'], [Object]);
            }
            if (data.hasOwnProperty('is_guest')) {
                obj['is_guest'] = ApiClient.convertToType(data['is_guest'], 'Boolean');
            }
            if (data.hasOwnProperty('is_phone_verified')) {
                obj['is_phone_verified'] = ApiClient.convertToType(data['is_phone_verified'], 'Boolean');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('merchant_id')) {
                obj['merchant_id'] = ApiClient.convertToType(data['merchant_id'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} created_at
 */
InlineResponse2009.prototype['created_at'] = undefined;

/**
 * @member {Object} deleted_at
 */
InlineResponse2009.prototype['deleted_at'] = undefined;

/**
 * @member {String} email
 */
InlineResponse2009.prototype['email'] = undefined;

/**
 * @member {String} first_name
 */
InlineResponse2009.prototype['first_name'] = undefined;

/**
 * @member {String} id
 */
InlineResponse2009.prototype['id'] = undefined;

/**
 * @member {Array.<Object>} identity_providers
 */
InlineResponse2009.prototype['identity_providers'] = undefined;

/**
 * @member {Boolean} is_guest
 */
InlineResponse2009.prototype['is_guest'] = undefined;

/**
 * @member {Boolean} is_phone_verified
 */
InlineResponse2009.prototype['is_phone_verified'] = undefined;

/**
 * @member {String} last_name
 */
InlineResponse2009.prototype['last_name'] = undefined;

/**
 * @member {String} merchant_id
 */
InlineResponse2009.prototype['merchant_id'] = undefined;

/**
 * @member {String} phone
 */
InlineResponse2009.prototype['phone'] = undefined;

/**
 * @member {String} updated_at
 */
InlineResponse2009.prototype['updated_at'] = undefined;






export default InlineResponse2009;

