/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MerchantsTransactionsPurchaseCreditCard from './MerchantsTransactionsPurchaseCreditCard';
import MerchantsTransactionsPurchaseSpecificFields from './MerchantsTransactionsPurchaseSpecificFields';

/**
 * The InlineObject6 model module.
 * @module model/InlineObject6
 * @version 1.0
 */
class InlineObject6 {
    /**
     * Constructs a new <code>InlineObject6</code>.
     * @alias module:model/InlineObject6
     */
    constructor() { 
        
        InlineObject6.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject6</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject6} obj Optional instance to populate.
     * @return {module:model/InlineObject6} The populated <code>InlineObject6</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject6();

            if (data.hasOwnProperty('billing_address')) {
                obj['billing_address'] = ApiClient.convertToType(data['billing_address'], Object);
            }
            if (data.hasOwnProperty('callback_url')) {
                obj['callback_url'] = ApiClient.convertToType(data['callback_url'], 'String');
            }
            if (data.hasOwnProperty('credit_card')) {
                obj['credit_card'] = MerchantsTransactionsPurchaseCreditCard.constructFromObject(data['credit_card']);
            }
            if (data.hasOwnProperty('device_id')) {
                obj['device_id'] = ApiClient.convertToType(data['device_id'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('method_type')) {
                obj['method_type'] = ApiClient.convertToType(data['method_type'], 'String');
            }
            if (data.hasOwnProperty('shipping_address')) {
                obj['shipping_address'] = ApiClient.convertToType(data['shipping_address'], Object);
            }
            if (data.hasOwnProperty('specific_fields')) {
                obj['specific_fields'] = MerchantsTransactionsPurchaseSpecificFields.constructFromObject(data['specific_fields']);
            }
            if (data.hasOwnProperty('store_code')) {
                obj['store_code'] = ApiClient.convertToType(data['store_code'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Object} billing_address
 */
InlineObject6.prototype['billing_address'] = undefined;

/**
 * @member {String} callback_url
 */
InlineObject6.prototype['callback_url'] = undefined;

/**
 * @member {module:model/MerchantsTransactionsPurchaseCreditCard} credit_card
 */
InlineObject6.prototype['credit_card'] = undefined;

/**
 * @member {String} device_id
 */
InlineObject6.prototype['device_id'] = undefined;

/**
 * @member {String} email
 */
InlineObject6.prototype['email'] = undefined;

/**
 * @member {String} method_type
 */
InlineObject6.prototype['method_type'] = undefined;

/**
 * @member {Object} shipping_address
 */
InlineObject6.prototype['shipping_address'] = undefined;

/**
 * @member {module:model/MerchantsTransactionsPurchaseSpecificFields} specific_fields
 */
InlineObject6.prototype['specific_fields'] = undefined;

/**
 * @member {String} store_code
 */
InlineObject6.prototype['store_code'] = undefined;

/**
 * @member {String} token
 */
InlineObject6.prototype['token'] = undefined;






export default InlineObject6;

