/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MerchantsTransactionsPurchaseCreditCard model module.
 * @module model/MerchantsTransactionsPurchaseCreditCard
 * @version 1.0
 */
class MerchantsTransactionsPurchaseCreditCard {
    /**
     * Constructs a new <code>MerchantsTransactionsPurchaseCreditCard</code>.
     * @alias module:model/MerchantsTransactionsPurchaseCreditCard
     * @param address1 {String} 
     * @param cardCvv {String} 
     * @param cardHolder {String} 
     * @param cardHolderDni {String} 
     * @param cardNumber {String} 
     * @param city {String} 
     * @param country {String} 
     * @param expiryMonth {String} 
     * @param expiryYear {String} 
     * @param phone {String} 
     * @param state {String} 
     * @param zip {String} 
     */
    constructor(address1, cardCvv, cardHolder, cardHolderDni, cardNumber, city, country, expiryMonth, expiryYear, phone, state, zip) { 
        
        MerchantsTransactionsPurchaseCreditCard.initialize(this, address1, cardCvv, cardHolder, cardHolderDni, cardNumber, city, country, expiryMonth, expiryYear, phone, state, zip);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, address1, cardCvv, cardHolder, cardHolderDni, cardNumber, city, country, expiryMonth, expiryYear, phone, state, zip) { 
        obj['address1'] = address1;
        obj['card_cvv'] = cardCvv;
        obj['card_holder'] = cardHolder;
        obj['card_holder_dni'] = cardHolderDni;
        obj['card_number'] = cardNumber;
        obj['city'] = city;
        obj['country'] = country;
        obj['expiry_month'] = expiryMonth;
        obj['expiry_year'] = expiryYear;
        obj['phone'] = phone;
        obj['state'] = state;
        obj['zip'] = zip;
    }

    /**
     * Constructs a <code>MerchantsTransactionsPurchaseCreditCard</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantsTransactionsPurchaseCreditCard} obj Optional instance to populate.
     * @return {module:model/MerchantsTransactionsPurchaseCreditCard} The populated <code>MerchantsTransactionsPurchaseCreditCard</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantsTransactionsPurchaseCreditCard();

            if (data.hasOwnProperty('address1')) {
                obj['address1'] = ApiClient.convertToType(data['address1'], 'String');
            }
            if (data.hasOwnProperty('card_cvv')) {
                obj['card_cvv'] = ApiClient.convertToType(data['card_cvv'], 'String');
            }
            if (data.hasOwnProperty('card_holder')) {
                obj['card_holder'] = ApiClient.convertToType(data['card_holder'], 'String');
            }
            if (data.hasOwnProperty('card_holder_dni')) {
                obj['card_holder_dni'] = ApiClient.convertToType(data['card_holder_dni'], 'String');
            }
            if (data.hasOwnProperty('card_number')) {
                obj['card_number'] = ApiClient.convertToType(data['card_number'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('expiry_month')) {
                obj['expiry_month'] = ApiClient.convertToType(data['expiry_month'], 'String');
            }
            if (data.hasOwnProperty('expiry_year')) {
                obj['expiry_year'] = ApiClient.convertToType(data['expiry_year'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('zip')) {
                obj['zip'] = ApiClient.convertToType(data['zip'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} address1
 */
MerchantsTransactionsPurchaseCreditCard.prototype['address1'] = undefined;

/**
 * @member {String} card_cvv
 */
MerchantsTransactionsPurchaseCreditCard.prototype['card_cvv'] = undefined;

/**
 * @member {String} card_holder
 */
MerchantsTransactionsPurchaseCreditCard.prototype['card_holder'] = undefined;

/**
 * @member {String} card_holder_dni
 */
MerchantsTransactionsPurchaseCreditCard.prototype['card_holder_dni'] = undefined;

/**
 * @member {String} card_number
 */
MerchantsTransactionsPurchaseCreditCard.prototype['card_number'] = undefined;

/**
 * @member {String} city
 */
MerchantsTransactionsPurchaseCreditCard.prototype['city'] = undefined;

/**
 * @member {String} country
 */
MerchantsTransactionsPurchaseCreditCard.prototype['country'] = undefined;

/**
 * @member {String} expiry_month
 */
MerchantsTransactionsPurchaseCreditCard.prototype['expiry_month'] = undefined;

/**
 * @member {String} expiry_year
 */
MerchantsTransactionsPurchaseCreditCard.prototype['expiry_year'] = undefined;

/**
 * @member {String} phone
 */
MerchantsTransactionsPurchaseCreditCard.prototype['phone'] = undefined;

/**
 * @member {String} state
 */
MerchantsTransactionsPurchaseCreditCard.prototype['state'] = undefined;

/**
 * @member {String} zip
 */
MerchantsTransactionsPurchaseCreditCard.prototype['zip'] = undefined;






export default MerchantsTransactionsPurchaseCreditCard;

