/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import InlineResponse2008 from '../model/InlineResponse2008';
import InlineResponse2009 from '../model/InlineResponse2009';

/**
* Users service.
* @module api/UsersApi
* @version 1.0
*/
export default class UsersApi {

    /**
    * Constructs a new UsersApi. 
    * @alias module:api/UsersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the usersLoginDeviceFingerprintPost operation.
     * @callback module:api/UsersApi~usersLoginDeviceFingerprintPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2008} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Login User
     * Login User
     * @param {Object} opts Optional parameters
     * @param {String} opts.xApiKey 
     * @param {String} opts.xMerchantId 
     * @param {String} opts.xDeviceId 
     * @param {String} opts.xSessionID 
     * @param {String} opts.authorization 
     * @param {String} opts.type 
     * @param {String} opts.loadProfileData 
     * @param {module:api/UsersApi~usersLoginDeviceFingerprintPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2008}
     */
    usersLoginDeviceFingerprintPost(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'type': opts['type'],
        'load_profile_data': opts['loadProfileData']
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey'],
        'X-Merchant-Id': opts['xMerchantId'],
        'X-Device-Id': opts['xDeviceId'],
        'X-Session-ID': opts['xSessionID'],
        'Authorization': opts['authorization']
      };
      let formParams = {
      };

      let authNames = ['Authorization', 'X-Api-Key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2008;
      return this.apiClient.callApi(
        '/users/login/device-fingerprint', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the usersMeGet operation.
     * @callback module:api/UsersApi~usersMeGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2009} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get User Information
     * Get User Information
     * @param {Object} opts Optional parameters
     * @param {String} opts.xApiKey 
     * @param {String} opts.xMerchantId 
     * @param {String} opts.xDeviceId 
     * @param {String} opts.authorization 
     * @param {module:api/UsersApi~usersMeGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2009}
     */
    usersMeGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey'],
        'X-Merchant-Id': opts['xMerchantId'],
        'X-Device-Id': opts['xDeviceId'],
        'Authorization': opts['authorization']
      };
      let formParams = {
      };

      let authNames = ['Authorization', 'X-Api-Key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2009;
      return this.apiClient.callApi(
        '/users/me', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
